name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
            cd /datafiles/meeting-nanaman-socket &&
            git pull origin main &&
            rm -rf node_modules && rm -rf dist &&
            npm install &&
            npm run build &&
            pm2 restart meeting-nanaman-socket || APP_CHAT_SOCKET_PORT=3002 pm2 start dist/index.js --name "meeting-nanaman-socket" &&
            pm2 save
          "